services:
  postgres:
    container_name: familybudget-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - familybudget_postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork 
    restart: always 

networks:
  mynetwork:
    driver: bridge

volumes:
  familybudget_postgres_data: